name: Run tests

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore & Build
        shell: bash
        run: |
          dotnet restore
          dotnet build -c Release --no-restore
      - name: Run unit tests
        run: |
          dotnet test -c Release --no-build \
            --logger "trx;LogFileName=test_results.trx" \
            --results-directory ./test-results
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Unit Tests
          path: test-results/*.trx
          reporter: dotnet-trx
          fail-on-error: true
          list-tests: 'all'
          list-suites: 'all'
          badge-title: 'unit-tests'
          use-actions-summary: 'true'
          only-summary: 'false'
